{
  "repository": {
    "name": "le-mystere-de-la-salle-jaune/evalme-back",
    "githubId": 140202858,
    "url": "https://github.com/le-mystere-de-la-salle-jaune/evalme-back",
    "isFork": false,
    "original": {
      "name": "",
      "githubId": 0,
      "url": ""
    },
    "isPullRequest": false,
    "pullRequestId": 0
  },
  "builds": {
    "buggyBuild": {
      "id": 405390913,
      "url": "http://travis-ci.org/le-mystere-de-la-salle-jaune/evalme-back/builds/405390913",
      "date": "Jul 18, 2018 10:51:14 AM"
    }
  },
  "reproductionBuggyBuild": {
    "reproductionDateBeginning": "Jul 18, 2018 10:55:44 AM",
    "reproductionDateEnd": "Jul 18, 2018 11:01:30 AM",
    "totalDuration": 341,
    "processDurations": {
      "cloning": {
        "nbSteps": 1,
        "totalDuration": 5,
        "stepNames": [
          "CloneRepository"
        ],
        "stepDurations": [
          5
        ]
      },
      "building": {
        "nbSteps": 2,
        "totalDuration": 46,
        "stepNames": [
          "CheckoutBuggyBuild",
          "BuildProject"
        ],
        "stepDurations": [
          0,
          46
        ]
      },
      "testing": {
        "nbSteps": 1,
        "totalDuration": 71,
        "stepNames": [
          "TestProject"
        ],
        "stepDurations": [
          71
        ]
      }
    },
    "projectRootPomPath": "./workspace/le-mystere-de-la-salle-jaune/evalme-back/405390913/pom.xml"
  },
  "patchDiff": {
    "files": {
      "numberAdded": 0,
      "numberChanged": 0,
      "numberDeleted": 0
    },
    "lines": {
      "numberAdded": 0,
      "numberDeleted": 0
    }
  },
  "commits": {
    "buggyBuild": {
      "repoName": "le-mystere-de-la-salle-jaune/evalme-back",
      "branchName": "classe-JPAV2",
      "sha": "3649cc8f2a29a9c08243b91b2f2e5917166b9e47",
      "url": "http://github.com/le-mystere-de-la-salle-jaune/evalme-back/commit/3649cc8f2a29a9c08243b91b2f2e5917166b9e47",
      "date": "Jul 18, 2018 10:49:46 AM"
    }
  },
  "projectMetrics": {
    "numberModules": 1,
    "numberSourceFiles": 114,
    "numberTestFiles": 45,
    "numberLibrariesFailingModule": 85
  },
  "tests": {
    "failingModule": "/root/workspace/le-mystere-de-la-salle-jaune/evalme-back/405390913",
    "overallMetrics": {
      "numberRunning": 139,
      "numberPassing": 133,
      "numberFailing": 2,
      "numberErroring": 4,
      "numberSkipping": 9,
      "failures": [
        {
          "failureName": "java.lang.IllegalArgumentException",
          "isError": true,
          "occurrences": 1
        },
        {
          "failureName": "org.springframework.dao.DataIntegrityViolationException",
          "isError": true,
          "occurrences": 2
        },
        {
          "failureName": "javax.persistence.PersistenceException",
          "isError": true,
          "occurrences": 1
        },
        {
          "failureName": "java.lang.AssertionError",
          "isError": false,
          "occurrences": 2
        }
      ]
    },
    "failingClasses": [
      {
        "testClass": "dev.repositories.classe.ClasseRepositoryDataJpaTest",
        "numberRunning": 6,
        "numberPassing": 3,
        "numberFailing": 1,
        "numberErroring": 2,
        "numberSkipping": 0
      },
      {
        "testClass": "dev.repositories.classe.ClasseRepositoryJdbcTest",
        "numberRunning": 5,
        "numberPassing": 4,
        "numberFailing": 0,
        "numberErroring": 1,
        "numberSkipping": 0
      },
      {
        "testClass": "dev.repositories.classe.ClasseRepositoryJPATest",
        "numberRunning": 5,
        "numberPassing": 3,
        "numberFailing": 1,
        "numberErroring": 1,
        "numberSkipping": 0
      }
    ],
    "failureDetails": [
      {
        "testClass": "dev.repositories.classe.ClasseRepositoryDataJpaTest",
        "testMethod": "testUpdate",
        "failureName": "java.lang.IllegalArgumentException",
        "detail": "org.hibernate.ObjectDeletedException: deleted instance passed to merge: [dev.entites.Classe#\u003cnull\u003e]",
        "isError": true
      },
      {
        "testClass": "dev.repositories.classe.ClasseRepositoryJPATest",
        "testMethod": "delete",
        "failureName": "org.springframework.dao.DataIntegrityViolationException",
        "detail": "could not execute statement; SQL [n/a]; constraint [\"CONSTRAINT_203: PUBLIC.DUEL FOREIGN KEY(STAGIAIREA_ID) REFERENCES PUBLIC.STAGIAIRE(ID) (1)\"; SQL statement:\ndelete from stagiaire where id\u003d? [23503-197]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement",
        "isError": true
      },
      {
        "testClass": "dev.repositories.classe.ClasseRepositoryJdbcTest",
        "testMethod": "testDelete",
        "failureName": "org.springframework.dao.DataIntegrityViolationException",
        "detail": "PreparedStatementCallback; SQL [DELETE FROM classe WHERE id \u003d ?Referential integrity constraint violation: \"CONSTRAINT_13: PUBLIC.STAGIAIRE FOREIGN KEY(ID_CLASSE) REFERENCES PUBLIC.CLASSE(ID) (1)\"; SQL statement:\nDELETE FROM classe WHERE id \u003d ? [23503-197]; nested exception is org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: \"CONSTRAINT_13: PUBLIC.STAGIAIRE FOREIGN KEY(ID_CLASSE) REFERENCES PUBLIC.CLASSE(ID) (1)\"; SQL statement:\nDELETE FROM classe WHERE id \u003d ? [23503-197]",
        "isError": true
      },
      {
        "testClass": "dev.repositories.classe.ClasseRepositoryJPATest",
        "testMethod": "test",
        "failureName": "java.lang.AssertionError",
        "detail": "Not yet implemented",
        "isError": false
      },
      {
        "testClass": "dev.repositories.classe.ClasseRepositoryDataJpaTest",
        "testMethod": "test",
        "failureName": "java.lang.AssertionError",
        "detail": "Not yet implemented",
        "isError": false
      },
      {
        "testClass": "dev.repositories.classe.ClasseRepositoryDataJpaTest",
        "testMethod": "delete",
        "failureName": "javax.persistence.PersistenceException",
        "detail": "org.hibernate.exception.ConstraintViolationException: could not execute statement",
        "isError": true
      }
    ]
  },
  "type": "only_fail"
}