{
  "repository": {
    "name": "nosan/embedded-cassandra",
    "githubId": 137877866,
    "url": "https://github.com/nosan/embedded-cassandra",
    "isFork": false,
    "original": {
      "name": "",
      "githubId": 0,
      "url": ""
    },
    "isPullRequest": false,
    "pullRequestId": 0
  },
  "builds": {
    "buggyBuild": {
      "id": 417221755,
      "url": "http://travis-ci.org/nosan/embedded-cassandra/builds/417221755",
      "date": "Aug 17, 2018 7:38:02 AM"
    }
  },
  "reproductionBuggyBuild": {
    "reproductionDateBeginning": "Aug 17, 2018 7:38:29 AM",
    "reproductionDateEnd": "Aug 17, 2018 7:41:29 AM",
    "totalDuration": 176,
    "processDurations": {
      "cloning": {
        "nbSteps": 1,
        "totalDuration": 4,
        "stepNames": [
          "CloneRepository"
        ],
        "stepDurations": [
          4
        ]
      },
      "building": {
        "nbSteps": 2,
        "totalDuration": 41,
        "stepNames": [
          "CheckoutBuggyBuild",
          "BuildProject"
        ],
        "stepDurations": [
          0,
          41
        ]
      },
      "testing": {
        "nbSteps": 1,
        "totalDuration": 57,
        "stepNames": [
          "TestProject"
        ],
        "stepDurations": [
          57
        ]
      }
    },
    "projectRootPomPath": "./workspace/nosan/embedded-cassandra/417221755/pom.xml"
  },
  "patchDiff": {
    "files": {
      "numberAdded": 0,
      "numberChanged": 0,
      "numberDeleted": 0
    },
    "lines": {
      "numberAdded": 0,
      "numberDeleted": 0
    }
  },
  "commits": {
    "buggyBuild": {
      "repoName": "nosan/embedded-cassandra",
      "branchName": "master",
      "sha": "5925fb7ee08bd5d55b571cf7301a216618921ba8",
      "url": "http://github.com/nosan/embedded-cassandra/commit/5925fb7ee08bd5d55b571cf7301a216618921ba8",
      "date": "Aug 17, 2018 7:29:37 AM"
    }
  },
  "projectMetrics": {
    "numberModules": 5,
    "numberSourceFiles": 57,
    "numberTestFiles": 50,
    "numberLibrariesFailingModule": 31
  },
  "tests": {
    "failingModule": "/root/workspace/nosan/embedded-cassandra/417221755/embedded-cassandra",
    "overallMetrics": {
      "numberRunning": 72,
      "numberPassing": 65,
      "numberFailing": 4,
      "numberErroring": 3,
      "numberSkipping": 0,
      "failures": [
        {
          "failureName": "java.lang.RuntimeException",
          "isError": true,
          "occurrences": 3
        },
        {
          "failureName": "java.lang.AssertionError",
          "isError": false,
          "occurrences": 4
        }
      ]
    },
    "failingClasses": [
      {
        "testClass": "com.github.nosan.embedded.cassandra.CassandraTests",
        "numberRunning": 7,
        "numberPassing": 0,
        "numberFailing": 4,
        "numberErroring": 3,
        "numberSkipping": 0
      }
    ],
    "failureDetails": [
      {
        "testClass": "com.github.nosan.embedded.cassandra.CassandraTests",
        "testMethod": "shouldBeAbleToRestartCassandra",
        "failureName": "java.lang.RuntimeException",
        "detail": "java.io.IOException: Could not start a process \u0027410\u0027. \u003cEOF\u003e",
        "isError": true
      },
      {
        "testClass": "com.github.nosan.embedded.cassandra.CassandraTests",
        "testMethod": "shouldBePossibleToStartMultiplyInstances",
        "failureName": "java.lang.RuntimeException",
        "detail": "java.io.IOException: Could not start a process \u0027758\u0027. \u003cEOF\u003e",
        "isError": true
      },
      {
        "testClass": "com.github.nosan.embedded.cassandra.CassandraTests",
        "testMethod": "shouldFailWithTimeoutError",
        "failureName": "java.lang.AssertionError",
        "detail": "\nExpected: (an instance of java.lang.RuntimeException and exception with message a string containing \"Please increase startup timeout\")\n     but: exception with message a string containing \"Please increase startup timeout\" message was \"java.io.IOException: Could not start a process \u0027827\u0027. \u003cEOF\u003e\"\nStacktrace was: java.lang.RuntimeException: java.io.IOException: Could not start a process \u0027827\u0027. \u003cEOF\u003e\n at com.github.nosan.embedded.cassandra.Cassandra.start(Cassandra.java:199)\n at com.github.nosan.embedded.cassandra.CassandraTests.run(CassandraTests.java:119)\n at com.github.nosan.embedded.cassandra.CassandraTests.shouldFailWithTimeoutError(CassandraTests.java:83)\n at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n at java.lang.reflect.Method.invoke(Method.java:498)\n at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)\n at org.junit.rules.RunRules.evaluate(RunRules.java:20)\n at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n at org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)\n at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)\n at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)\n at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)\n at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)\n at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)\n at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)\nCaused by: java.io.IOException: Could not start a process \u0027827\u0027. \u003cEOF\u003e\n at com.github.nosan.embedded.cassandra.process.CassandraProcess.start(CassandraProcess.java:94)\n at com.github.nosan.embedded.cassandra.Cassandra$CassandraExecutable.start(Cassandra.java:271)\n at com.github.nosan.embedded.cassandra.Cassandra.start(Cassandra.java:195)\n ... 28 more\n",
        "isError": false
      },
      {
        "testClass": "com.github.nosan.embedded.cassandra.CassandraTests",
        "testMethod": "shouldFailWithInvalidConfigurationError",
        "failureName": "java.lang.AssertionError",
        "detail": "\nExpected: (an instance of java.lang.RuntimeException and exception with message a string containing \"Missing required directive CommitLogSync\")\n     but: exception with message a string containing \"Missing required directive CommitLogSync\" message was \"java.io.IOException: Could not start a process \u0027551\u0027. \u003cEOF\u003e\"\nStacktrace was: java.lang.RuntimeException: java.io.IOException: Could not start a process \u0027551\u0027. \u003cEOF\u003e\n at com.github.nosan.embedded.cassandra.Cassandra.start(Cassandra.java:199)\n at com.github.nosan.embedded.cassandra.CassandraTests.run(CassandraTests.java:119)\n at com.github.nosan.embedded.cassandra.CassandraTests.shouldFailWithInvalidConfigurationError(CassandraTests.java:74)\n at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n at java.lang.reflect.Method.invoke(Method.java:498)\n at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)\n at org.junit.rules.RunRules.evaluate(RunRules.java:20)\n at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n at org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)\n at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)\n at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)\n at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)\n at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)\n at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)\n at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)\nCaused by: java.io.IOException: Could not start a process \u0027551\u0027. \u003cEOF\u003e\n at com.github.nosan.embedded.cassandra.process.CassandraProcess.start(CassandraProcess.java:94)\n at com.github.nosan.embedded.cassandra.Cassandra$CassandraExecutable.start(Cassandra.java:271)\n at com.github.nosan.embedded.cassandra.Cassandra.start(Cassandra.java:195)\n ... 28 more\n",
        "isError": false
      },
      {
        "testClass": "com.github.nosan.embedded.cassandra.CassandraTests",
        "testMethod": "shouldNotStartCassandraIfCassandraHasBeenAlreadyStarted",
        "failureName": "java.lang.AssertionError",
        "detail": "\nExpected: (an instance of java.lang.IllegalStateException and exception with message a string containing \"Cassandra has already been initialized\")\n     but: an instance of java.lang.IllegalStateException \u003cjava.lang.RuntimeException: java.io.IOException: Could not start a process \u0027480\u0027. \u003cEOF\u003e\u003e is a java.lang.RuntimeException\nStacktrace was: java.lang.RuntimeException: java.io.IOException: Could not start a process \u0027480\u0027. \u003cEOF\u003e\n at com.github.nosan.embedded.cassandra.Cassandra.start(Cassandra.java:199)\n at com.github.nosan.embedded.cassandra.CassandraTests.run(CassandraTests.java:128)\n at com.github.nosan.embedded.cassandra.CassandraTests.shouldNotStartCassandraIfCassandraHasBeenAlreadyStarted(CassandraTests.java:47)\n at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n at java.lang.reflect.Method.invoke(Method.java:498)\n at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)\n at org.junit.rules.RunRules.evaluate(RunRules.java:20)\n at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n at org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)\n at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)\n at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)\n at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)\n at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)\n at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)\n at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)\nCaused by: java.io.IOException: Could not start a process \u0027480\u0027. \u003cEOF\u003e\n at com.github.nosan.embedded.cassandra.process.CassandraProcess.start(CassandraProcess.java:94)\n at com.github.nosan.embedded.cassandra.Cassandra$CassandraExecutable.start(Cassandra.java:271)\n at com.github.nosan.embedded.cassandra.Cassandra.start(Cassandra.java:195)\n ... 28 more\n",
        "isError": false
      },
      {
        "testClass": "com.github.nosan.embedded.cassandra.CassandraTests",
        "testMethod": "shouldStartCassandraWithDisableRpcAndNativeTransportPorts",
        "failureName": "java.lang.AssertionError",
        "detail": "\nExpected: (an instance of java.net.ConnectException and exception with message a string containing \"Connection refused\")\n     but: an instance of java.net.ConnectException \u003cjava.lang.RuntimeException: java.io.IOException: Could not start a process \u0027689\u0027. \u003cEOF\u003e\u003e is a java.lang.RuntimeException\nStacktrace was: java.lang.RuntimeException: java.io.IOException: Could not start a process \u0027689\u0027. \u003cEOF\u003e\n at com.github.nosan.embedded.cassandra.Cassandra.start(Cassandra.java:199)\n at com.github.nosan.embedded.cassandra.CassandraTests.run(CassandraTests.java:128)\n at com.github.nosan.embedded.cassandra.CassandraTests.shouldStartCassandraWithDisableRpcAndNativeTransportPorts(CassandraTests.java:104)\n at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n at java.lang.reflect.Method.invoke(Method.java:498)\n at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)\n at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)\n at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)\n at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)\n at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)\n at org.junit.rules.RunRules.evaluate(RunRules.java:20)\n at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)\n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)\n at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)\n at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\n at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\n at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\n at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\n at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\n at org.junit.runners.ParentRunner.run(ParentRunner.java:363)\n at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)\n at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)\n at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)\n at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)\n at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)\n at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)\n at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)\nCaused by: java.io.IOException: Could not start a process \u0027689\u0027. \u003cEOF\u003e\n at com.github.nosan.embedded.cassandra.process.CassandraProcess.start(CassandraProcess.java:94)\n at com.github.nosan.embedded.cassandra.Cassandra$CassandraExecutable.start(Cassandra.java:271)\n at com.github.nosan.embedded.cassandra.Cassandra.start(Cassandra.java:195)\n ... 28 more\n",
        "isError": false
      },
      {
        "testClass": "com.github.nosan.embedded.cassandra.CassandraTests",
        "testMethod": "shouldStartCassandraUsingRpcTransport",
        "failureName": "java.lang.RuntimeException",
        "detail": "java.io.IOException: Could not start a process \u0027620\u0027. \u003cEOF\u003e",
        "isError": true
      }
    ]
  },
  "type": "only_fail"
}