{
  "repository": {
    "name": "isopov/tarantool-java-driver",
    "githubId": 94575707,
    "url": "https://github.com/isopov/tarantool-java-driver",
    "isFork": false,
    "original": {
      "name": "",
      "githubId": 0,
      "url": ""
    },
    "isPullRequest": false,
    "pullRequestId": 0
  },
  "builds": {
    "buggyBuild": {
      "id": 404211383,
      "url": "http://travis-ci.org/isopov/tarantool-java-driver/builds/404211383",
      "date": "Jul 15, 2018 4:18:40 PM"
    }
  },
  "reproductionBuggyBuild": {
    "reproductionDateBeginning": "Jul 15, 2018 4:18:57 PM",
    "reproductionDateEnd": "Jul 15, 2018 4:21:27 PM",
    "totalDuration": 147,
    "processDurations": {
      "cloning": {
        "nbSteps": 1,
        "totalDuration": 5,
        "stepNames": [
          "CloneRepository"
        ],
        "stepDurations": [
          5
        ]
      },
      "building": {
        "nbSteps": 2,
        "totalDuration": 63,
        "stepNames": [
          "CheckoutBuggyBuild",
          "BuildProject"
        ],
        "stepDurations": [
          0,
          63
        ]
      },
      "testing": {
        "nbSteps": 1,
        "totalDuration": 20,
        "stepNames": [
          "TestProject"
        ],
        "stepDurations": [
          20
        ]
      },
      "fixing": {
        "nbSteps": 3,
        "totalDuration": 38,
        "stepNames": [
          "Nopol",
          "NPEFix",
          "AstorJMut"
        ],
        "stepDurations": [
          32,
          0,
          6
        ]
      }
    },
    "projectRootPomPath": "./workspace/isopov/tarantool-java-driver/404211383/pom.xml"
  },
  "patchDiff": {
    "files": {
      "numberAdded": 0,
      "numberChanged": 0,
      "numberDeleted": 0
    },
    "lines": {
      "numberAdded": 0,
      "numberDeleted": 0
    }
  },
  "commits": {
    "buggyBuild": {
      "repoName": "isopov/tarantool-java-driver",
      "branchName": "async",
      "sha": "13d4d3a619a493a9b9f89957e5ff471cf01f81a3",
      "url": "http://github.com/isopov/tarantool-java-driver/commit/13d4d3a619a493a9b9f89957e5ff471cf01f81a3",
      "date": "Jul 15, 2018 4:15:21 PM"
    }
  },
  "projectMetrics": {
    "numberModules": 8,
    "numberSourceFiles": 36,
    "numberTestFiles": 14,
    "numberLibrariesFailingModule": 5
  },
  "tests": {
    "failingModule": "/root/workspace/isopov/tarantool-java-driver/404211383/tarantool-driver",
    "overallMetrics": {
      "numberRunning": 74,
      "numberPassing": 26,
      "numberFailing": 18,
      "numberErroring": 30,
      "numberSkipping": 0,
      "failures": [
        {
          "failureName": "java.lang.AssertionError",
          "isError": false,
          "occurrences": 18
        },
        {
          "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
          "isError": true,
          "occurrences": 30
        }
      ]
    },
    "failingClasses": [
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "numberRunning": 25,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 25,
        "numberSkipping": 0
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolAsyncClientTest",
        "numberRunning": 3,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 3,
        "numberSkipping": 0
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "numberRunning": 35,
        "numberPassing": 15,
        "numberFailing": 18,
        "numberErroring": 2,
        "numberSkipping": 0
      }
    ],
    "failureDetails": [
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testUpdate",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testGetVersion",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testConnect",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testSelectByName",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testManySelects",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testUpdateBytes",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testIsClosed",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testSetDoubleWithoutInsert",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolException and exception with message a string containing \"Need to call one of update/insert/upsert/delete before setting tuple value\")      but: exception with message a string containing \"Need to call one of update/insert/upsert/delete before setting tuple value\" message was \"java.net.ConnectException: Connection refused (Connection refused)\" Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testException(TarantoolClientImplExceptionsTest.java:284)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testSetWithoutAction(TarantoolClientImplExceptionsTest.java:290)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testSetDoubleWithoutInsert(TarantoolClientImplExceptionsTest.java:72)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 36 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testClosedPing",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testDoubleUpsertWithoutExecute",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolException and exception with message a string containing \"Execute or add to batch action before starting next one\")      but: exception with message a string containing \"Execute or add to batch action before starting next one\" message was \"java.net.ConnectException: Connection refused (Connection refused)\" Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testException(TarantoolClientImplExceptionsTest.java:284)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testPreActionCheck(TarantoolClientImplExceptionsTest.java:294)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testDoubleUpsertWithoutExecute(TarantoolClientImplExceptionsTest.java:133)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 36 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testSetIntWithoutInsert",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolException and exception with message a string containing \"Need to call one of update/insert/upsert/delete before setting tuple value\")      but: exception with message a string containing \"Need to call one of update/insert/upsert/delete before setting tuple value\" message was \"java.net.ConnectException: Connection refused (Connection refused)\" Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testException(TarantoolClientImplExceptionsTest.java:284)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testSetWithoutAction(TarantoolClientImplExceptionsTest.java:290)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testSetIntWithoutInsert(TarantoolClientImplExceptionsTest.java:57)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 36 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testSetNullWithoutInsert",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolException and exception with message a string containing \"Need to call one of update/insert/upsert/delete before setting tuple value\")      but: exception with message a string containing \"Need to call one of update/insert/upsert/delete before setting tuple value\" message was \"java.net.ConnectException: Connection refused (Connection refused)\" Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testException(TarantoolClientImplExceptionsTest.java:284)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testSetWithoutAction(TarantoolClientImplExceptionsTest.java:290)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testSetNullWithoutInsert(TarantoolClientImplExceptionsTest.java:82)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 36 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testWrongUser",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolAuthException and exception with message a string containing \"User \u0027barfoo\u0027 is not found\")      but: an instance of com.sopovs.moradanen.tarantool.core.TarantoolAuthException \u003ccom.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)\u003e is a com.sopovs.moradanen.tarantool.core.TarantoolException Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplTest.testAuth(TarantoolClientImplTest.java:29)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testWrongUser(TarantoolClientImplExceptionsTest.java:43)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 35 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testWrongPassword",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolAuthException and exception with message a string containing \"Incorrect password supplied for user \u0027foobar\u0027\")      but: an instance of com.sopovs.moradanen.tarantool.core.TarantoolAuthException \u003ccom.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)\u003e is a com.sopovs.moradanen.tarantool.core.TarantoolException Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplTest.testAuth(TarantoolClientImplTest.java:29)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testWrongPassword(TarantoolClientImplExceptionsTest.java:36)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 35 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testReplace",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testUpsert",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testChangeAfterInsert",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolException and exception with message a string containing \"Need to call update/upsert before change\")      but: exception with message a string containing \"Need to call update/upsert before change\" message was \"java.net.ConnectException: Connection refused (Connection refused)\" Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testException(TarantoolClientImplExceptionsTest.java:284)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testChangeAfterInsert(TarantoolClientImplExceptionsTest.java:92)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 35 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testDoubleEvalWithoutExecute",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolException and exception with message a string containing \"Execute or add to batch action before starting next one\")      but: exception with message a string containing \"Execute or add to batch action before starting next one\" message was \"java.net.ConnectException: Connection refused (Connection refused)\" Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testException(TarantoolClientImplExceptionsTest.java:284)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testPreActionCheck(TarantoolClientImplExceptionsTest.java:294)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testDoubleEvalWithoutExecute(TarantoolClientImplExceptionsTest.java:113)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 36 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testChangeAfterSelect",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolException and exception with message a string containing \"Need to call update/upsert before change\")      but: exception with message a string containing \"Need to call update/upsert before change\" message was \"java.net.ConnectException: Connection refused (Connection refused)\" Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testException(TarantoolClientImplExceptionsTest.java:284)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testChangeAfterSelect(TarantoolClientImplExceptionsTest.java:100)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 35 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testAuthSuccess",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolAsyncClientTest",
        "testMethod": "testConnect",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testInsert",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testSetFloatWithoutInsert",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolException and exception with message a string containing \"Need to call one of update/insert/upsert/delete before setting tuple value\")      but: exception with message a string containing \"Need to call one of update/insert/upsert/delete before setting tuple value\" message was \"java.net.ConnectException: Connection refused (Connection refused)\" Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testException(TarantoolClientImplExceptionsTest.java:284)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testSetWithoutAction(TarantoolClientImplExceptionsTest.java:290)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testSetFloatWithoutInsert(TarantoolClientImplExceptionsTest.java:67)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 36 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testExecuteCreateTable",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testChangeWithoutUpdate",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolException and exception with message a string containing \"Need to call update/upsert before change\")      but: exception with message a string containing \"Need to call update/upsert before change\" message was \"java.net.ConnectException: Connection refused (Connection refused)\" Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testException(TarantoolClientImplExceptionsTest.java:284)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testChangeWithoutUpdate(TarantoolClientImplExceptionsTest.java:87)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 35 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testDoubleUpdateWithoutExecute",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolException and exception with message a string containing \"Execute or add to batch action before starting next one\")      but: exception with message a string containing \"Execute or add to batch action before starting next one\" message was \"java.net.ConnectException: Connection refused (Connection refused)\" Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testException(TarantoolClientImplExceptionsTest.java:284)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testPreActionCheck(TarantoolClientImplExceptionsTest.java:294)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testDoubleUpdateWithoutExecute(TarantoolClientImplExceptionsTest.java:128)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 36 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testUpdateString",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolAsyncClientTest",
        "testMethod": "test2Ping",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testUpsertBatch",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testSetLongWithoutInsert",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolException and exception with message a string containing \"Need to call one of update/insert/upsert/delete before setting tuple value\")      but: exception with message a string containing \"Need to call one of update/insert/upsert/delete before setting tuple value\" message was \"java.net.ConnectException: Connection refused (Connection refused)\" Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testException(TarantoolClientImplExceptionsTest.java:284)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testSetWithoutAction(TarantoolClientImplExceptionsTest.java:290)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testSetLongWithoutInsert(TarantoolClientImplExceptionsTest.java:62)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 36 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testGetStringNull",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testNoSpace",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolException and exception with message a string containing \"No such space no_such_space\")      but: exception with message a string containing \"No such space no_such_space\" message was \"java.net.ConnectException: Connection refused (Connection refused)\" Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testNoSpace(TarantoolClientImplExceptionsTest.java:50)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 34 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testInsertBatch",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testUpdateIntAssign",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testSpace",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testExecuteWithoutAction",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolException and exception with message a string containing \"Trying to execute absent query\")      but: exception with message a string containing \"Trying to execute absent query\" message was \"java.net.ConnectException: Connection refused (Connection refused)\" Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testException(TarantoolClientImplExceptionsTest.java:284)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testExecuteWithoutAction(TarantoolClientImplExceptionsTest.java:108)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 35 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testDoubleSelectWithoutExecute",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolException and exception with message a string containing \"Execute or add to batch action before starting next one\")      but: exception with message a string containing \"Execute or add to batch action before starting next one\" message was \"java.net.ConnectException: Connection refused (Connection refused)\" Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testException(TarantoolClientImplExceptionsTest.java:284)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testPreActionCheck(TarantoolClientImplExceptionsTest.java:294)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testDoubleSelectWithoutExecute(TarantoolClientImplExceptionsTest.java:118)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 36 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testEval",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolAsyncClientTest",
        "testMethod": "testPing",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testInsertAndSelect",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testUpdateLong",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testPing",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testDelete",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testDoubleInsertWithoutExecute",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolException and exception with message a string containing \"Execute or add to batch action before starting next one\")      but: exception with message a string containing \"Execute or add to batch action before starting next one\" message was \"java.net.ConnectException: Connection refused (Connection refused)\" Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testException(TarantoolClientImplExceptionsTest.java:284)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testPreActionCheck(TarantoolClientImplExceptionsTest.java:294)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testDoubleInsertWithoutExecute(TarantoolClientImplExceptionsTest.java:123)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 36 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testDeleteComposite",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testUpdateIntString",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest",
        "testMethod": "testSetBooleanWithoutInsert",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of com.sopovs.moradanen.tarantool.core.TarantoolException and exception with message a string containing \"Need to call one of update/insert/upsert/delete before setting tuple value\")      but: exception with message a string containing \"Need to call one of update/insert/upsert/delete before setting tuple value\" message was \"java.net.ConnectException: Connection refused (Connection refused)\" Stacktrace was: com.sopovs.moradanen.tarantool.core.TarantoolException: java.net.ConnectException: Connection refused (Connection refused)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:93)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:82)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.\u003cinit\u003e(TarantoolClientImpl.java:78)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testException(TarantoolClientImplExceptionsTest.java:284)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testSetWithoutAction(TarantoolClientImplExceptionsTest.java:290)  at com.sopovs.moradanen.tarantool.TarantoolClientImplExceptionsTest.testSetBooleanWithoutInsert(TarantoolClientImplExceptionsTest.java:77)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: java.net.ConnectException: Connection refused (Connection refused)  at java.net.PlainSocketImpl.socketConnect(Native Method)  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)  at java.net.Socket.connect(Socket.java:589)  at java.net.Socket.connect(Socket.java:538)  at java.net.Socket.\u003cinit\u003e(Socket.java:434)  at java.net.Socket.\u003cinit\u003e(Socket.java:211)  at com.sopovs.moradanen.tarantool.TarantoolClientImpl.createSocket(TarantoolClientImpl.java:91)  ... 36 more ",
        "isError": false
      },
      {
        "testClass": "com.sopovs.moradanen.tarantool.TarantoolClientImplTest",
        "testMethod": "testSelect",
        "failureName": "com.sopovs.moradanen.tarantool.core.TarantoolException",
        "detail": "java.net.ConnectException: Connection refused (Connection refused)",
        "isError": true
      }
    ]
  },
  "type": "only_fail"
}