-------------------------------------------------------------------------------
Test set: br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 7.656 s <<< FAILURE! - in br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest
testBuscarLancamentosPorFuncionarioId(br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest)  Time elapsed: 2.023 s  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest.setUp(LancamentoRepositoryTest.java:45)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest.setUp(LancamentoRepositoryTest.java:45)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest.setUp(LancamentoRepositoryTest.java:45)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest.setUp(LancamentoRepositoryTest.java:45)

testBuscarLancamentosPorFuncionarioId(br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest)  Time elapsed: 2.023 s  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest.tearDown(LancamentoRepositoryTest.java:56)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest.tearDown(LancamentoRepositoryTest.java:56)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest.tearDown(LancamentoRepositoryTest.java:56)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest.tearDown(LancamentoRepositoryTest.java:56)

testBuscarLancamentosPorFuncionarioIdPaginado(br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest)  Time elapsed: 2.019 s  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest.setUp(LancamentoRepositoryTest.java:45)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest.setUp(LancamentoRepositoryTest.java:45)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest.setUp(LancamentoRepositoryTest.java:45)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest.setUp(LancamentoRepositoryTest.java:45)

testBuscarLancamentosPorFuncionarioIdPaginado(br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest)  Time elapsed: 2.019 s  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest.tearDown(LancamentoRepositoryTest.java:56)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest.tearDown(LancamentoRepositoryTest.java:56)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest.tearDown(LancamentoRepositoryTest.java:56)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at br.com.modelo.pontointeligente.api.repositories.LancamentoRepositoryTest.tearDown(LancamentoRepositoryTest.java:56)

