-------------------------------------------------------------------------------
Test set: org.apache.calcite.test.LatticeTest
-------------------------------------------------------------------------------
Tests run: 38, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 213.658 s <<< FAILURE! - in org.apache.calcite.test.LatticeTest
testTileAlgorithm(org.apache.calcite.test.LatticeTest)  Time elapsed: 132.708 s  <<< ERROR!
java.lang.RuntimeException: 
exception while executing [explain plan for select distinct t."the_year", t."quarter"
from "foodmart"."sales_fact_1997" as s
join "foodmart"."time_by_day" as t using ("time_id")
]
	at org.apache.calcite.test.LatticeTest.checkTileAlgorithm(LatticeTest.java:463)
	at org.apache.calcite.test.LatticeTest.testTileAlgorithm(LatticeTest.java:423)
Caused by: java.lang.RuntimeException: While populating materialization [adhoc, m{16, 17, 27, 31, 32, 37}]
	at org.apache.calcite.test.LatticeTest.checkTileAlgorithm(LatticeTest.java:463)
	at org.apache.calcite.test.LatticeTest.testTileAlgorithm(LatticeTest.java:423)
Caused by: java.lang.RuntimeException: 
while executing SQL [SELECT "t0"."recyclable_package", "t0"."low_fat", "t1"."the_year", "t1"."quarter", "t1"."fiscal_period", "t2"."product_family", COUNT(*) AS "m0", SUM("t"."store_sales") AS "m1", SUM("t"."unit_sales") AS "m2"
FROM (SELECT "product_id", "time_id", "store_sales", "unit_sales"
FROM "foodmart"."sales_fact_1997") AS "t"
INNER JOIN (SELECT "product_class_id", "product_id", "recyclable_package", "low_fat"
FROM "foodmart"."product") AS "t0" ON "t"."product_id" = "t0"."product_id"
INNER JOIN (SELECT "time_id", "the_year", "quarter", "fiscal_period"
FROM "foodmart"."time_by_day") AS "t1" ON "t"."time_id" = "t1"."time_id"
INNER JOIN (SELECT "product_class_id", "product_family"
FROM "foodmart"."product_class") AS "t2" ON "t0"."product_class_id" = "t2"."product_class_id"
GROUP BY "t0"."recyclable_package", "t0"."low_fat", "t1"."the_year", "t1"."quarter", "t1"."fiscal_period", "t2"."product_family"]
	at org.apache.calcite.test.LatticeTest.checkTileAlgorithm(LatticeTest.java:463)
	at org.apache.calcite.test.LatticeTest.testTileAlgorithm(LatticeTest.java:423)
Caused by: java.sql.SQLTransactionRollbackException: statement execution aborted: timeout reached
	at org.apache.calcite.test.LatticeTest.checkTileAlgorithm(LatticeTest.java:463)
	at org.apache.calcite.test.LatticeTest.testTileAlgorithm(LatticeTest.java:423)
Caused by: org.hsqldb.HsqlException: statement execution aborted: timeout reached
	at org.apache.calcite.test.LatticeTest.checkTileAlgorithm(LatticeTest.java:463)
	at org.apache.calcite.test.LatticeTest.testTileAlgorithm(LatticeTest.java:423)

